In [4]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Load the data

In [5]:
data = pd.read_csv("/content/drive/MyDrive/Data_Analyst/Data_Analyst_Details/Weather_data/Weather_Data.csv")

In [ ]:
data

             Date/Time  Temp_C  ...  Press_kPa               Weather
0        1/1/2012 0:00    -1.8  ...     101.24                   Fog
1        1/1/2012 1:00    -1.8  ...     101.24                   Fog
2        1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3        1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4        1/1/2012 4:00    -1.5  ...     101.23                   Fog
...                ...     ...  ...        ...                   ...
8779  12/31/2012 19:00     0.1  ...     100.13                  Snow
8780  12/31/2012 20:00     0.2  ...     100.03                  Snow
8781  12/31/2012 21:00    -0.5  ...      99.95                  Snow
8782  12/31/2012 22:00    -0.2  ...      99.91                  Snow
8783  12/31/2012 23:00     0.0  ...      99.89                  Snow

[8784 rows x 8 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [ ]:
data.shape

(8784, 8)

In [ ]:
data.index

RangeIndex(start=0, stop=8784, step=1)

In [ ]:
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [ ]:
data['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [ ]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [ ]:
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [ ]:
data['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Moderate Snow                                 4
Freezing Fog                                  4
Snow Showers,Fog                              4
Thunderstorms,Rain                            3
Rain,Haze                                     3
Thunderstorms,Rain Showers,Fog                3
Freezing Drizzle,Haze                         3
Freezing Rain,Haze                            2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Snow Showers                     2
Drizzle,Snow                                  2
Snow Pellets                                  1
Freezing Rain,Snow Grains                     1
Rain,Snow Grains                              1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Moderate Rain,Fog                             1
Rain,Snow,Fog                                 1
Freezing Rain,Ice Pellets,Fog                 1
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Heavy Rain Showers              1
Name: Weather, dtype: int64

Q. 1)  Find all the unique 'Wind Speed' values in the data.

In [ ]:
data['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

Q. 2) Find the number of times when the 'Weather is exactly Clear'.

Step 1: apply function(Here is count function)   
Step 2: Filtering function    
Step 3: Groupby function

In [ ]:
data['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Moderate Snow                                 4
Freezing Fog                                  4
Snow Showers,Fog                              4
Thunderstorms,Rain                            3
Rain,Haze                                     3
Thunderstorms,Rain Showers,Fog                3
Freezing Drizzle,Haze                         3
Freezing Rain,Haze                            2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Snow Showers                     2
Drizzle,Snow                                  2
Snow Pellets                                  1
Freezing Rain,Snow Grains                     1
Rain,Snow Grains                              1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Moderate Rain,Fog                             1
Rain,Snow,Fog                                 1
Freezing Rain,Ice Pellets,Fog                 1
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Heavy Rain Showers              1
Name: Weather, dtype: int64

In [ ]:
data.Weather == 'Clear'

0       False
1       False
2       False
3       False
4       False
        ...
8779    False
8780    False
8781    False
8782    False
8783    False
Name: Weather, Length: 8784, dtype: bool

In [ ]:
data[data.Weather == 'Clear']

             Date/Time  Temp_C  ...  Press_kPa  Weather
67      1/3/2012 19:00   -16.9  ...     101.74    Clear
114     1/5/2012 18:00    -7.1  ...     100.71    Clear
115     1/5/2012 19:00    -9.2  ...     100.80    Clear
116     1/5/2012 20:00    -9.8  ...     100.83    Clear
117     1/5/2012 21:00    -9.0  ...     100.83    Clear
...                ...     ...  ...        ...      ...
8646   12/26/2012 6:00   -13.4  ...     102.47    Clear
8698  12/28/2012 10:00    -6.1  ...     101.27    Clear
8713   12/29/2012 1:00   -11.9  ...     101.31    Clear
8714   12/29/2012 2:00   -11.8  ...     101.33    Clear
8756  12/30/2012 20:00   -13.8  ...     101.52    Clear

[1326 rows x 8 columns]

In [ ]:
data.groupby('Weather').get_group('Clear')

             Date/Time  Temp_C  ...  Press_kPa  Weather
67      1/3/2012 19:00   -16.9  ...     101.74    Clear
114     1/5/2012 18:00    -7.1  ...     100.71    Clear
115     1/5/2012 19:00    -9.2  ...     100.80    Clear
116     1/5/2012 20:00    -9.8  ...     100.83    Clear
117     1/5/2012 21:00    -9.0  ...     100.83    Clear
...                ...     ...  ...        ...      ...
8646   12/26/2012 6:00   -13.4  ...     102.47    Clear
8698  12/28/2012 10:00    -6.1  ...     101.27    Clear
8713   12/29/2012 1:00   -11.9  ...     101.31    Clear
8714   12/29/2012 2:00   -11.8  ...     101.33    Clear
8756  12/30/2012 20:00   -13.8  ...     101.52    Clear

[1326 rows x 8 columns]

Q. 3) Find the number of times when the 'Wind Speed was exactly 4 km/h'.

In [ ]:
data[data.Wind Speed_km/h = 4]

SyntaxError: ignored

In [ ]:
data[data['Wind Speed_km/h'] == 4]

             Date/Time  Temp_C  ...  Press_kPa       Weather
0        1/1/2012 0:00    -1.8  ...     101.24           Fog
1        1/1/2012 1:00    -1.8  ...     101.24           Fog
96       1/5/2012 0:00    -8.8  ...     100.32          Snow
101      1/5/2012 5:00    -7.0  ...     100.19          Snow
146      1/7/2012 2:00    -8.1  ...     100.15        Cloudy
...                ...     ...  ...        ...           ...
8768   12/31/2012 8:00    -8.6  ...     101.14  Snow Showers
8769   12/31/2012 9:00    -8.1  ...     101.09          Snow
8770  12/31/2012 10:00    -7.4  ...     101.05      Snow,Fog
8772  12/31/2012 12:00    -5.8  ...     100.78          Snow
8773  12/31/2012 13:00    -4.6  ...     100.63          Snow

[474 rows x 8 columns]

Q. 4) Find out all the Null Values in the data.

In [ ]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [ ]:
data.notnull().sum()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

Q. 5) Rename the column name 'Weather' of the dataframe to 'Weather Condition'.

In [ ]:
data.rename(columns = {'Weather' : 'Weather Condition'}, inplace = True)

In [ ]:
data.head(5)

       Date/Time  Temp_C  ...  Press_kPa     Weather Condition
0  1/1/2012 0:00    -1.8  ...     101.24                   Fog
1  1/1/2012 1:00    -1.8  ...     101.24                   Fog
2  1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3  1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4  1/1/2012 4:00    -1.5  ...     101.23                   Fog

[5 rows x 8 columns]

Q. 6) What is the mean 'Visibility' ?

In [ ]:
data.Visibility_km.mean()

27.66444672131151

Q. 7) What is the Standard Deviation of 'Pressure'  in this data?

In [ ]:
data.Press_kPa.std()

0.8440047459486474

Q. 8) What is the Variance of 'Relative Humidity' in this data ?

In [ ]:
data['Rel Hum_%'].var()

286.2485501984998

Q. 9) Find all instances when 'Snow' was recorded.

In [ ]:
data['Weather Condition'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Moderate Snow                                 4
Freezing Fog                                  4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Snow Showers,Fog                              4
Thunderstorms,Rain                            3
Rain,Haze                                     3
Freezing Drizzle,Haze                         3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Rain Showers,Snow Showers                     2
Thunderstorms,Rain,Fog                        1
Snow Pellets                                  1
Rain,Snow Grains                              1
Freezing Rain,Snow Grains                     1
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Heavy Rain Showers              1
Moderate Rain,Fog                             1
Rain,Snow,Fog                                 1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Freezing Rain,Ice Pellets,Fog                 1
Name: Weather Condition, dtype: int64

In [ ]:
data[data['Weather Condition'] == 'Snow'].value_counts()

Date/Time        Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  Visibility_km  Press_kPa  Weather Condition
4/27/2012 9:00    2.7    -3.2              65         32               24.1           100.40     Snow                 1
1/9/2012 11:00   -3.7    -7.2              77         7                24.1           101.54     Snow                 1
1/6/2012 3:00    -10.6   -16.0             64         0                9.7            100.76     Snow                 1
1/6/2012 4:00    -11.3   -16.1             68         15               3.2            100.70     Snow                 1
1/6/2012 5:00    -11.8   -16.0             71         19               2.8            100.61     Snow                 1
                                                                                                                     ..
2/15/2012 12:00   2.1    -0.3              84         0                9.7            101.67     Snow                 1
2/15/2012 13:00   1.7    -0.3              87         6                9.7            101.67     Snow                 1
2/15/2012 14:00   1.5     0.0              90         7                9.7            101.68     Snow                 1
2/15/2012 21:00   1.3     0.1              92         13               8.0            101.95     Snow                 1
1/10/2012 1:00    2.3    -3.4              66         35               25.0           100.28     Snow                 1
Length: 390, dtype: int64

In [ ]:
#str.contains = matched full and partial string
data[data['Weather Condition'].str.contains('Snow')]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
41      1/2/2012 17:00    -2.1  ...      99.66       Snow Showers
44      1/2/2012 20:00    -5.6  ...     100.07       Snow Showers
45      1/2/2012 21:00    -5.8  ...     100.15       Snow Showers
47      1/2/2012 23:00    -7.4  ...     100.27       Snow Showers
48       1/3/2012 0:00    -9.0  ...     100.35       Snow Showers
...                ...     ...  ...        ...                ...
8779  12/31/2012 19:00     0.1  ...     100.13               Snow
8780  12/31/2012 20:00     0.2  ...     100.03               Snow
8781  12/31/2012 21:00    -0.5  ...      99.95               Snow
8782  12/31/2012 22:00    -0.2  ...      99.91               Snow
8783  12/31/2012 23:00     0.0  ...      99.89               Snow

[583 rows x 8 columns]

Q. 10) Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'.

In [ ]:
data[(data['Wind Speed_km/h'] > 24) & (data.Visibility_km > 25)]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
109     1/5/2012 13:00    -4.4  ...     100.40       Mainly Clear
111     1/5/2012 15:00    -4.3  ...     100.52       Mainly Clear
350    1/15/2012 14:00   -16.0  ...     102.66       Mainly Clear
422    1/18/2012 14:00   -10.3  ...     101.19       Mainly Clear
423    1/18/2012 15:00   -10.4  ...     101.32       Mainly Clear
...                ...     ...  ...        ...                ...
8748  12/30/2012 12:00   -12.2  ...     100.91      Mostly Cloudy
8749  12/30/2012 13:00   -12.4  ...     100.92      Mostly Cloudy
8750  12/30/2012 14:00   -11.8  ...     100.96       Mainly Clear
8751  12/30/2012 15:00   -11.3  ...     101.05       Mainly Clear
8752  12/30/2012 16:00   -11.4  ...     101.15       Mainly Clear

[232 rows x 8 columns]

Q. 11) What is the Mean value of each column against each 'Weather Condition ?

In [ ]:
data.groupby('Weather Condition').mean()

                                            Temp_C  ...   Press_kPa
Weather Condition                                   ...
Clear                                     6.825716  ...  101.587443
Cloudy                                    7.970544  ...  100.911441
Drizzle                                   7.353659  ...  100.435366
Drizzle,Fog                               8.067500  ...  100.786625
Drizzle,Ice Pellets,Fog                   0.400000  ...  100.790000
Drizzle,Snow                              1.050000  ...  100.890000
Drizzle,Snow,Fog                          0.693333  ...   99.281333
Fog                                       4.303333  ...  101.184067
Freezing Drizzle                         -5.657143  ...  100.202857
Freezing Drizzle,Fog                     -2.533333  ...  100.441667
Freezing Drizzle,Haze                    -5.433333  ...  100.316667
Freezing Drizzle,Snow                    -5.109091  ...  100.520909
Freezing Fog                             -7.575000  ...  102.320000
Freezing Rain                            -3.885714  ...   99.647143
Freezing Rain,Fog                        -2.225000  ...   99.945000
Freezing Rain,Haze                       -4.900000  ...  100.375000
Freezing Rain,Ice Pellets,Fog            -2.600000  ...  100.950000
Freezing Rain,Snow Grains                -5.000000  ...   98.560000
Haze                                     -0.200000  ...  101.482500
Mainly Clear                             12.558927  ...  101.248832
Moderate Rain,Fog                         1.700000  ...   99.980000
Moderate Snow                            -5.525000  ...  100.275000
Moderate Snow,Blowing Snow               -5.450000  ...  100.570000
Mostly Cloudy                            10.574287  ...  101.025288
Rain                                      9.786275  ...  100.233333
Rain Showers                             13.722340  ...  100.404043
Rain Showers,Fog                         12.800000  ...   99.830000
Rain Showers,Snow Showers                 2.150000  ...  101.100000
Rain,Fog                                  8.273276  ...  100.500862
Rain,Haze                                 4.633333  ...  100.540000
Rain,Ice Pellets                          0.600000  ...  100.120000
Rain,Snow                                 1.055556  ...   99.951111
Rain,Snow Grains                          1.900000  ...  100.600000
Rain,Snow,Fog                             0.800000  ...  100.730000
Rain,Snow,Ice Pellets                     1.100000  ...  100.105000
Snow                                     -4.524103  ...  100.536103
Snow Pellets                              0.700000  ...   99.700000
Snow Showers                             -3.506667  ...  100.963500
Snow Showers,Fog                        -10.675000  ...  101.292500
Snow,Blowing Snow                        -5.410526  ...   99.704737
Snow,Fog                                 -5.075676  ...  100.688649
Snow,Haze                                -4.020000  ...  100.782000
Snow,Ice Pellets                         -1.883333  ...  100.548333
Thunderstorms                            24.150000  ...  100.230000
Thunderstorms,Heavy Rain Showers         10.900000  ...  100.260000
Thunderstorms,Moderate Rain Showers,Fog  19.600000  ...  100.010000
Thunderstorms,Rain                       20.433333  ...  100.420000
Thunderstorms,Rain Showers               20.037500  ...  100.233750
Thunderstorms,Rain Showers,Fog           21.600000  ...  100.063333
Thunderstorms,Rain,Fog                   20.600000  ...  100.080000

[50 rows x 6 columns]

Q. 13) Show all the Records where Weather Condition is Fog.

In [ ]:
data[data['Weather Condition'] == 'Fog']

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
0        1/1/2012 0:00    -1.8  ...     101.24                Fog
1        1/1/2012 1:00    -1.8  ...     101.24                Fog
4        1/1/2012 4:00    -1.5  ...     101.23                Fog
5        1/1/2012 5:00    -1.4  ...     101.27                Fog
6        1/1/2012 6:00    -1.5  ...     101.29                Fog
...                ...     ...  ...        ...                ...
8716   12/29/2012 4:00   -16.0  ...     101.25                Fog
8717   12/29/2012 5:00   -14.8  ...     101.25                Fog
8718   12/29/2012 6:00   -13.8  ...     101.25                Fog
8719   12/29/2012 7:00   -14.8  ...     101.22                Fog
8722  12/29/2012 10:00   -12.0  ...     101.15                Fog

[150 rows x 8 columns]

Q. 14) Find all instances when 'Weather is Clear' or 'Visibility is above 40'.

In [ ]:
data[(data['Weather Condition'] == 'Clear') & (data.Visibility_km > 40)]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
351    1/15/2012 15:00   -15.4  ...     102.71              Clear
352    1/15/2012 16:00   -15.1  ...     102.79              Clear
425    1/18/2012 17:00   -11.3  ...     101.54              Clear
440     1/19/2012 8:00   -13.7  ...     101.84              Clear
441     1/19/2012 9:00   -12.7  ...     101.73              Clear
...                ...     ...  ...        ...                ...
8384   12/15/2012 8:00   -10.7  ...     102.69              Clear
8385   12/15/2012 9:00   -10.4  ...     102.74              Clear
8389  12/15/2012 13:00    -8.4  ...     102.64              Clear
8631  12/25/2012 15:00    -7.1  ...     101.98              Clear
8632  12/25/2012 16:00    -7.5  ...     102.03              Clear

[313 rows x 8 columns]

Q. 15) Find all instances when :   
A. 'Weather is Clear' and 'Relative Humidity is greater than 50'  
or  
B. 'Visibility is above 40'

In [ ]:
data[(data['Weather Condition'] == 'Clear') & (data['Rel Hum_%'] > 50) | (data.Visibility_km > 40)]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
106     1/5/2012 10:00    -6.0  ...     100.45       Mainly Clear
107     1/5/2012 11:00    -5.6  ...     100.41       Mainly Clear
108     1/5/2012 12:00    -4.7  ...     100.38       Mainly Clear
109     1/5/2012 13:00    -4.4  ...     100.40       Mainly Clear
110     1/5/2012 14:00    -5.1  ...     100.46       Mainly Clear
...                ...     ...  ...        ...                ...
8749  12/30/2012 13:00   -12.4  ...     100.92      Mostly Cloudy
8750  12/30/2012 14:00   -11.8  ...     100.96       Mainly Clear
8751  12/30/2012 15:00   -11.3  ...     101.05       Mainly Clear
8752  12/30/2012 16:00   -11.4  ...     101.15       Mainly Clear
8756  12/30/2012 20:00   -13.8  ...     101.52              Clear

[2921 rows x 8 columns]